## Path to your oh-my-zsh installation
export ZSH=$HOME/.oh-my-zsh

export LSCOLORS='exfxcxdxbxegedabagacad'
export CLICOLOR=true

## Set name of the theme to load.
## Look in ~/.oh-my-zsh/themes/
#ZSH_THEME="dracula"
# ZSH_THEME="dallas"
# ZSH_THEME="gnzh"
# ZSH_THEME="jonathan"
ZSH_THEME="fino-time"
# ZSH_THEME="passion"

## oh-my-zsh plugins
plugins=(git npm zsh-nvm)

# User configuration

## Path
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
#export MANPATH="/usr/local/man:$MANPATH"

## Path to oh-my-zsh script
source $ZSH/oh-my-zsh.sh

## custom aliases
source ~/dotfiles/oh-my-zsh/aliases

## Setting vim as default editor
export EDITOR="vim"

## Postgres path
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/10/bin

## Adding RVM & other rails related to the path
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/sbin:$PATH"
export PATH="/usr/local/opt/openssl/bin:$PATH"
export PATH="/usr/local/opt/qt/bin:$PATH"
export PATH="/usr/local/opt/qt@5.5/bin:$PATH"

## Adding z script path for easy cding...
## Source: https://github.com/rupa/z
. ~/dotfiles/oh-my-zsh/z.sh

## Yarn pkg manager path
export PATH="$HOME/.yarn/bin:$PATH"

## NVM path
export NVM_LAZY_LOAD=true
export NVM_AUTO_USE=true

## To set node packages path
## Allow global npm install without sudo
## Source: (https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md)
NPM_PACKAGES="${HOME}/.npm-packages"
NODE_PATH="$NPM_PACKAGES/lib/node_modules:$NODE_PATH"
PATH="$NPM_PACKAGES/bin:$PATH"

## Unset manpath so we can inherit from /etc/manpath via the `manpath`
unset MANPATH ## delete if you already modified MANPATH elsewhere in your config
MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

clear

## END

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
# export PATH="/usr/local/opt/icu4c/bin:$PATH"
# export PATH="/usr/local/opt/icu4c/sbin:$PATH"

# export YVM_DIR=/usr/local/opt/yvm
[ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh

export YVM_DIR=/Users/logeshpaul/.yvm
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
